name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug environment variables
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          echo "=== DEBUGGING SIGNING SETUP ==="
          echo "TAURI_SIGNING_PRIVATE_KEY length: ${#TAURI_SIGNING_PRIVATE_KEY}"
          echo "TAURI_SIGNING_PRIVATE_KEY_PASSWORD length: ${#TAURI_SIGNING_PRIVATE_KEY_PASSWORD}"
          echo "First 50 chars of key: ${TAURI_SIGNING_PRIVATE_KEY:0:50}..."
          echo "Key ends with: ...${TAURI_SIGNING_PRIVATE_KEY: -20}"
          echo "Password is set: $([ -n "$TAURI_SIGNING_PRIVATE_KEY_PASSWORD" ] && echo "YES" || echo "NO")"
          
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install

      - name: Debug and clean private key
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          echo "=== COMPREHENSIVE KEY ANALYSIS ==="
          echo "Key length: ${#TAURI_SIGNING_PRIVATE_KEY}"
          echo "Password length: ${#TAURI_SIGNING_PRIVATE_KEY_PASSWORD}"
          
          echo "=== RAW KEY INSPECTION ==="
          echo "First 100 chars: ${TAURI_SIGNING_PRIVATE_KEY:0:100}"
          echo "Last 50 chars: ${TAURI_SIGNING_PRIVATE_KEY: -50}"
          
          echo "=== CHARACTER ANALYSIS AROUND OFFSET 464 ==="
          if [ ${#TAURI_SIGNING_PRIVATE_KEY} -gt 470 ]; then
            echo "Characters 460-470:"
            echo "${TAURI_SIGNING_PRIVATE_KEY:460:10}" | od -c
            echo "Characters as hex:"
            echo "${TAURI_SIGNING_PRIVATE_KEY:460:10}" | xxd
          fi
          
          echo "=== LOOKING FOR EMBEDDED NEWLINES ==="
          echo "Checking for \\n characters in key:"
          echo "$TAURI_SIGNING_PRIVATE_KEY" | grep -o $'\n' | wc -l || echo "grep failed"
          
          echo "=== ATTEMPTING TO CLEAN KEY ==="
          # Method 1: Remove all whitespace and re-encode
          echo "Method 1: Strip whitespace and decode/re-encode..."
          CLEAN_KEY_1=$(echo "$TAURI_SIGNING_PRIVATE_KEY" | tr -d '\n\r\t ' | base64 -d 2>/dev/null | base64 2>/dev/null || echo "FAILED")
          echo "Clean key 1 result: ${CLEAN_KEY_1:0:50}... (length: ${#CLEAN_KEY_1})"
          
          # Method 2: Direct character replacement  
          echo "Method 2: Replace problematic sequences..."
          CLEAN_KEY_2=$(echo "$TAURI_SIGNING_PRIVATE_KEY" | sed 's/Cl//g' | tr -d '\n\r\t ')
          echo "Clean key 2 result: ${CLEAN_KEY_2:0:50}... (length: ${#CLEAN_KEY_2})"
          
          echo "=== TESTING CLEANED KEYS ==="
          for i in 1 2; do
            eval "TEST_KEY=\$CLEAN_KEY_$i"
            if [ "$TEST_KEY" != "FAILED" ] && [ ${#TEST_KEY} -gt 100 ]; then
              echo "Testing cleaned key method $i..."
              echo "$TEST_KEY" > "/tmp/clean_key_$i.key"
              echo "test content" > "/tmp/test_$i.txt"
              
              if npx tauri signer sign "/tmp/test_$i.txt" -f "/tmp/clean_key_$i.key" -p "$TAURI_SIGNING_PRIVATE_KEY_PASSWORD" 2>&1; then
                echo "✅ CLEANED KEY METHOD $i SUCCEEDED!"
                echo "🎯 USE THIS KEY IN GITHUB SECRETS:"
                echo "$TEST_KEY"
                echo "🎯 END OF CLEAN KEY"
                break
              else
                echo "❌ Cleaned key method $i failed"
              fi
            else
              echo "Cleaned key method $i is invalid"
            fi
          done
          
          echo "=== ORIGINAL KEY TEST (for comparison) ==="
          echo "$TAURI_SIGNING_PRIVATE_KEY" > /tmp/original_key.key
          echo "test content original" > /tmp/test_original.txt
          npx tauri signer sign /tmp/test_original.txt -f /tmp/original_key.key -p "$TAURI_SIGNING_PRIVATE_KEY_PASSWORD" 2>&1 || echo "Original key failed as expected"
          
          # Clean up
          rm -f /tmp/*_key*.key /tmp/test*.txt

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'ManyMany.dev v__VERSION__ (Debug Build)'
          releaseBody: |
            ## Debug Release v__VERSION__
            
            This is a debug build to test the signing and update system.
            
            **What we're testing:**
            - Proper code signing with corrected key pair
            - Automatic generation of latest.json with real signatures
            - End-to-end update functionality
            
            **Technical details:**
            - ARM-only build for Apple Silicon Macs
            - Enhanced logging for signing diagnostics
            - Version: __VERSION__
          releaseDraft: false
          prerelease: false
          args: --target aarch64-apple-darwin
          includeUpdaterJson: true

      - name: Debug build artifacts and signing results
        run: |
          echo "=== POST-BUILD ARTIFACT ANALYSIS ==="
          
          echo "🔍 Searching for signature files..."
          find src-tauri/target -name "*.sig" -ls || echo "❌ No .sig files found"
          
          echo "🔍 Searching for tar.gz files..."
          find src-tauri/target -name "*.tar.gz*" -ls
          
          echo "🔍 Checking bundle directory structure..."
          find src-tauri/target -type f -name "*ManyMany*" | head -20
          
          echo "🔍 Looking for any signing-related files..."
          find src-tauri/target -name "*sign*" -o -name "*.key" -o -name "*.pub" | head -10
          
          echo "🔍 Directory structure of release bundle..."
          ls -la src-tauri/target/aarch64-apple-darwin/release/bundle/ || echo "Bundle directory not found"
          
          if [ -d "src-tauri/target/aarch64-apple-darwin/release/bundle/macos" ]; then
            echo "📁 macOS bundle contents:"
            ls -la src-tauri/target/aarch64-apple-darwin/release/bundle/macos/
          fi
